### ISSUE TITLE
BUG - Lib can't verify payment addresses and hashed payloads

### ISSUE THREAD

**Issue by gitmachtl** [cardano-foundation/cardano-verify-datasignature#9] opened 2022-12-17 20:39 UTC
## Payment addresses

Did some testing, and it looks like the lib v1.0.5 is not able to use payment addresses.  But CIP-30 actually is fine with payment addresses/keys. I get errors when using a payment address with the function like below:

```js
try {
        var result = verifyDataSignature(signature, key, message, stakeAddress);
} catch (error) { console.error(error) };
```

```
Error: Invalid Address
    at e.getAddressFromBech32 (/node_modules/@cardano-foundation/cardano-verify-datasignature/dist/index.js:2:61557)
    at u (/node_modules/@cardano-foundation/cardano-verify-datasignature/dist/index.js:2:433408)
```

Yes i know, its stated as stakeAddress. But than its not fully CIP-30 compatible.

-----

## Hashed payloads

Also, the lib can't handle **hashed** payloads. Here is some data, which should be **valid**, but the lib is reporting **false**.

This is an unhashed payload, the lib returns **true** which is correct:
```json
{
  "workMode": "sign-cip30",
  "addressHex": "e0c13582aec9a44fcc6d984be003c5058c660e1d2ff1370fd8b49ba73f",
  "inputDataHex": "48656c6c6f20776f726c64",
  "isHashed": "false",
  "signDataHex": "846a5369676e617475726531582aa201276761646472657373581de0c13582aec9a44fcc6d984be003c5058c660e1d2ff1370fd8b49ba73f404b48656c6c6f20776f726c64",
  "signDataSignature": "0a0dd23e867292a4c2eb692f63016e3f61294686f672065fcc377f665cff6b25c430619060b536073cfd2355ab6c6bcec9d7ecbfb588f7b0aa5967f1b8559300",
  "secretKey": "c14ef0cc5e352446d6243976f51e8ffb2ae257f2a547c4fba170964a76501e7a",
  "publicKey": "9be513df12b3fabe7c1b8c3f9fab0968eb2168d5689bf981c2f7c35b11718b27",
  "signedMessage": "cms_hFgqogEnZ2FkZHJlc3NYHeDBNYKuyaRPzG2YS-ADxQWMZg4dL_E3D9i0m6c_oWZoYXNoZWT0S0hlbGxvIHdvcmxkWEAKDdI-hnKSpMLraS9jAW4_YSlGhvZyBl_MN39mXP9rJcQwYZBgtTYHPP0jVatsa87J1-y_tYj3sKpZZ_G4VZMALw5uNA",
  "COSE_Sign1_hex": "84582aa201276761646472657373581de0c13582aec9a44fcc6d984be003c5058c660e1d2ff1370fd8b49ba73fa166686173686564f44b48656c6c6f20776f726c6458400a0dd23e867292a4c2eb692f63016e3f61294686f672065fcc377f665cff6b25c430619060b536073cfd2355ab6c6bcec9d7ecbfb588f7b0aa5967f1b8559300",
  "COSE_Key_hex": "a40101032720062158209be513df12b3fabe7c1b8c3f9fab0968eb2168d5689bf981c2f7c35b11718b27"
}
```
```js
console.log(verifyDataSignature(COSE_Sign1_hex, COSE_Key_hex));
true
```

This is a hashed payload, the lib returns **false**, which is NOT correct:

```json
{
  "workMode": "sign-cip30",
  "addressHex": "e0c13582aec9a44fcc6d984be003c5058c660e1d2ff1370fd8b49ba73f",
  "inputDataHex": "48656c6c6f20776f726c64",
  "isHashed": "true",
  "hashedInputDataHex": "40843181253eb1ff2258ab39c3463ec0edf5e713b73c5482c0ca798f",
  "signDataHex": "846a5369676e617475726531582aa201276761646472657373581de0c13582aec9a44fcc6d984be003c5058c660e1d2ff1370fd8b49ba73f40581c40843181253eb1ff2258ab39c3463ec0edf5e713b73c5482c0ca798f",
  "signDataSignature": "a4cdec07ba8c1184aa74d1c3516fc6602a35d2db847510cf98c102653c15c7664f136314f920150a081870aef77ed49780ca58873bd5d62e744b968a89435906",
  "secretKey": "c14ef0cc5e352446d6243976f51e8ffb2ae257f2a547c4fba170964a76501e7a",
  "publicKey": "9be513df12b3fabe7c1b8c3f9fab0968eb2168d5689bf981c2f7c35b11718b27",
  "signedMessage": "cms_hFgqogEnZ2FkZHJlc3NYHeDBNYKuyaRPzG2YS-ADxQWMZg4dL_E3D9i0m6c_oWZoYXNoZWT1WBxAhDGBJT6x_yJYqznDRj7A7fXnE7c8VILAynmPWECkzewHuowRhKp00cNRb8ZgKjXS24R1EM-YwQJlPBXHZk8TYxT5IBUKCBhwrvd-1JeAyliHO9XWLnRLloqJQ1kG49cjVw",
  "COSE_Sign1_hex": "84582aa201276761646472657373581de0c13582aec9a44fcc6d984be003c5058c660e1d2ff1370fd8b49ba73fa166686173686564f5581c40843181253eb1ff2258ab39c3463ec0edf5e713b73c5482c0ca798f5840a4cdec07ba8c1184aa74d1c3516fc6602a35d2db847510cf98c102653c15c7664f136314f920150a081870aef77ed49780ca58873bd5d62e744b968a89435906",
  "COSE_Key_hex": "a40101032720062158209be513df12b3fabe7c1b8c3f9fab0968eb2168d5689bf981c2f7c35b11718b27"
}
```
```js
console.log(verifyDataSignature(COSE_Sign1_hex, COSE_Key_hex));
false
```

Used address: `stake_test1urqntq4wexjylnrdnp97qq79qkxxvrsa9lcnwr7ckjd6w0cr04y4p`
Used payload: `Hello world`

-----

## Documentation

Also, there is a bit of a documentation lack how the functions
```js
verifyDataSignature(signature, key, message)
verifyDataSignature(signature, key, message, stakeAddress)
```
do the check. Is a given `message` replacing an existing one in the signature? Same for the `stakeAddress`, is it comparing the given address with the one stored in the inner cbor payload or is it just using the given one and it tries a verification on it?

Thx, best regards, Martin

**Comment by fabianbormann** [comment] 2022-12-17 22:45
Thanks for the detailed issue description! 😊 If this is ok for you I would like to add your examples to the test cases and of course fix the wrong behavior and improve the docs.

Best regards, Fabian

**Comment by gitmachtl** [comment] 2022-12-18 07:49
Hi @fabianbormann, i talked with Ashish (strica) and there was a bug in there lib. So when you upgrade your package to `v1.0.3` of [@stricahq/cip08](https://github.com/StricaHQ/cip08) the hashed payload should work. Not sure about the payment address.

**Comment by fabianbormann** [comment] 2022-12-18 08:04
@gitmachtl nice thanks! I already saw that and updated the version and the test case with the hashed payload now returns true as expected. I will adjust the docs and push in a few minutes. I'm in ECT and just woke up but kudos to you and Ashish to get things work while I was sleeping 😄

**Comment by fabianbormann** [comment] 2022-12-18 08:53
With regards to the address.. I know what's the issue and I know what I need to do, but I will be able to solve this in the evening at the earliest or maybe tomorrow because of a familiy event today. 

The option to provide the bech32 address came from a request to check if a (non enterprise) payment address belongs to a stake address that was used to sign the message. 

So I use the stake credential of the address to get the stake address and compare it with the provided key. 

But if the key is a payment address and you provide this optional bech32 address it will obviously fail. 

So I need another if statement to check if the key belongs to a stake or payment address right before the extraction of the stake credential - which I don't need to do in case of a payment key was used to sign the message.

Best regards, Fabian 😊

**Comment by gitmachtl** [comment] 2022-12-18 08:56
Also - not sure how to solve this - maybe with another option in the function inputs, but the functions
```js
verifyDataSignature(signature, key, message)
verifyDataSignature(signature, key, message, stakeAddress)
```
currently always return **false** for COSE_Sign1 with hashed payloads. because there is no switch to tell the function to compare the signing with the hashed message, and not with the non-hashed message like now. question is if this should be left as it is, but stated that these functions use non-hashed messages?

**Comment by fabianbormann** [comment] 2022-12-18 11:24
Ah no problem I get the info if it's hashed or not from the Cose_Sign1 so if the message does not match the regex of a hash and the hashed_input field of Cose_Sign1 is true I will hash the message and perform the check

**Comment by fabianbormann** [comment] 2022-12-19 17:51
@gitmachtl I think I covered now all the cases mentioned within this issue. 😊 Would be great if you could provide some feedback and close this issue if everything works as expected.

**Comment by gitmachtl** [comment] 2022-12-19 19:51
Hashed content is working now, but payment addresses are still failing with lib v1.0.8:

```json
{
  "workMode": "sign-cip30",
  "addressHex": "617863b5c43bdf0a06608abc82f0573a549714ff69166074dcdde393d8",
  "addressType": "payment enterprise",
  "addressNetwork": "mainnet",
  "inputDataHex": "48656c6c6f20776f726c64",
  "isHashed": "false",
  "signDataHex": "846a5369676e617475726531582aa201276761646472657373581d617863b5c43bdf0a06608abc82f0573a549714ff69166074dcdde393d8404b48656c6c6f20776f726c64",
  "signature": "fc58155f0cee05bc00e7299af1df1f159ac82a46a055786b259657934eff346eec81349d4678ceabc79f213c66a2bdbfd4ea5d9ebdc630bee5ac9cce75cfc001",
  "secretKey": "16275bd6647f94a53e9fe1c71439a258a03c13cadf32935ed5388972ebd7e53f",
  "publicKey": "755b017578b701dc9ddd4eaee67015b4ca8baf66293b7b1d204df426c0ceccb9",
  "output": {
    "signedMessage": "cms_hFgqogEnZ2FkZHJlc3NYHWF4Y7XEO98KBmCKvILwVzpUlxT_aRZgdNzd45PYoWZoYXNoZWT0S0hlbGxvIHdvcmxkWED8WBVfDO4FvADnKZrx3x8VmsgqRqBVeGsllleTTv80buyBNJ1GeM6rx58hPGaivb_U6l2evcYwvuWsnM51z8ABZWrr1w",
    "COSE_Sign1_hex": "84582aa201276761646472657373581d617863b5c43bdf0a06608abc82f0573a549714ff69166074dcdde393d8a166686173686564f44b48656c6c6f20776f726c645840fc58155f0cee05bc00e7299af1df1f159ac82a46a055786b259657934eff346eec81349d4678ceabc79f213c66a2bdbfd4ea5d9ebdc630bee5ac9cce75cfc001",
    "COSE_Key_hex": "a4010103272006215820755b017578b701dc9ddd4eaee67015b4ca8baf66293b7b1d204df426c0ceccb9"
  }
}
```
Payload: `Hello world`
Address: `addr1v9ux8dwy800s5pnq327g9uzh8f2fw98ldytxqaxumh3e8kqumfr6d`

COSE_Sign1 content:
```
84                                     # array(4)
   58 2a                               #   bytes(42)
      a201276761646472657373581d617863 #     "\xa2\x01\'gaddressX\x1daxc"
      b5c43bdf0a06608abc82f0573a549714 #     "\xb5\xc4;\xdf\n\x06`\x8a\xbc\x82\xf0W:T\x97\x14"
      ff69166074dcdde393d8             #     "\xffi\x16`t\xdc\xdd\xe3\x93\xd8"
   a1                                  #   map(1)
      66                               #     text(6)
         686173686564                  #       "hashed"
      f4                               #     false, simple(20)
   4b                                  #   bytes(11)
      48656c6c6f20776f726c64           #     "Hello world"
   58 40                               #   bytes(64)
      fc58155f0cee05bc00e7299af1df1f15 #     "\xfcX\x15_\x0c\xee\x05\xbc\x00\xe7)\x9a\xf1\xdf\x1f\x15"
      9ac82a46a055786b259657934eff346e #     "\x9a\xc8*F\xa0Uxk%\x96W\x93N\xff4n"
      ec81349d4678ceabc79f213c66a2bdbf #     "\xec\x814\x9dFx\xce\xab\xc7\x9f!<f\xa2\xbd\xbf"
      d4ea5d9ebdc630bee5ac9cce75cfc001 #     "\xd4\xea]\x9e\xbd\xc60\xbe\xe5\xac\x9c\xceu\xcf\xc0\x01"
```
```js
try {
        console.log(verifyDataSignature( COSE_Sign1_cbor_hex, COSE_Key_cbor_hex, 'Hello world', 'addr1v9ux8dwy800s5pnq327g9uzh8f2fw98ldytxqaxumh3e8kqumfr6d'));
} catch (error) {console.error(error)}

TypeError: Cannot read properties of undefined (reading 'type')
    at a.computeHex (/node_modules/@cardano-foundation/cardano-verify-datasignature/dist/index.js:2:24022)
    at new a (/node_modules/@cardano-foundation/cardano-verify-datasignature/dist/index.js:2:23858)
    at f (/node_modules/@cardano-foundation/cardano-verify-datasignature/dist/index.js:2:433992)
...
```

**Comment by gitmachtl** [comment] 2022-12-19 22:10
By the way, i released v1.12.0 of cardano-signer (https://github.com/gitmachtl/cardano-signer/releases/latest). Would be nice if you could add it to your readme in the `How to get a cip30 datasignature?` section. Its currently the only tool to do signing/verification of CIP-8/CIP-30 stuff on the cli.  
You can find a simple CIP-30 dataset generation example here: https://github.com/gitmachtl/cardano-signer#cip-8--cip-30-mode
And you can replace --cip8 with --cip30, they are idential currently. ❤️

**Comment by fabianbormann** [comment] 2022-12-19 22:58
Nice sure 🎉! I will add it to the Readme tomorrow and also look at the payment addresses 👍🏻

**Closed as completed** 2022-12-20 15:34 UTC
Labels: bug

**Comment by fabianbormann** [comment] 2022-12-20 15:39
@gitmachtl I closed the issue automatically with my commit message.. but it should actually be closed this time 🤞. If you see any other unexpected behavior it would maybe make sense to open a new issue. The problem was that I tried to extract the stake credential for the verification but the payment address you used was an enterprise address so there was no stake credential and I had to add another condition to cover this case. I also added cardano signer to the Readme 😊
